# Generated by Django 3.0.8 on 2020-08-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='credentialId',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='grade',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='institute',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='profilepic',
            name='status',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='issuedDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
