# Generated by Django 3.0.8 on 2020-08-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile1', '0002_auto_20200826_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
    ]
