# Generated by Django 3.1 on 2020-09-01 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(blank=True, default='', max_length=100)),
                ('uploadFile', models.FileField(upload_to='documents')),
                ('description', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdocument', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
