# Generated by Django 3.1 on 2020-09-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='uploadedOn',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
