# Generated by Django 3.1 on 2020-09-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_uploadedon'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='fileExtension',
            field=models.TextField(default='', null=True),
        ),
    ]
