# Generated by Django 3.1 on 2020-09-07 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='active',
            new_name='private',
        ),
    ]
