# Generated by Django 3.1 on 2020-09-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20200907_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='private',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
