# Generated by Django 3.0.8 on 2020-08-07 15:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUUIDModel',
            fields=[
                ('Member_Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField(blank=True)),
                ('Attestant', models.TextField(blank=True)),
                ('Date', models.DateField(null=True)),
                ('Designation', models.TextField(blank=True)),
                ('Location', models.TextField(blank=True)),
                ('Member_Id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='UserModule.MyUUIDModel')),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.TextField(blank=True)),
                ('Member_Id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='UserModule.MyUUIDModel')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country_Code', models.IntegerField()),
                ('Phone', models.IntegerField()),
                ('Email_Id', models.EmailField(blank=True, max_length=320)),
                ('Member_Id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='UserModule.MyUUIDModel')),
            ],
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(blank=True, max_length=20)),
                ('Last_Name', models.CharField(blank=True, max_length=20)),
                ('Profile_Pic_URL', models.ImageField(upload_to='profile_pics')),
                ('Bio', models.TextField(blank=True)),
                ('Tag_Line', models.TextField(blank=True)),
                ('profile_Status', models.IntegerField(default=0)),
                ('Status', models.TextField(blank=True)),
                ('Member_Id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='UserModule.MyUUIDModel')),
            ],
        ),
        migrations.CreateModel(
            name='KeySKills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skills', models.TextField(blank=True)),
                ('Member_Id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='UserModule.MyUUIDModel')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_Title', models.TextField(blank=True)),
                ('Timings', models.DateTimeField(null=True)),
                ('Description', models.TextField(blank=True)),
                ('EventDate', models.DateField(null=True)),
                ('LinkToDoc', models.URLField(blank=True)),
                ('Member_Id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='UserModule.MyUUIDModel')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Institution_Name', models.CharField(blank=True, max_length=100)),
                ('Degree', models.CharField(blank=True, max_length=50)),
                ('Field_Of_Study', models.TextField(blank=True)),
                ('Grade', models.FloatField()),
                ('Start_Date', models.DateField(null=True)),
                ('End_Date', models.DateField(null=True)),
                ('Description', models.TextField(blank=True)),
                ('Member_Id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='UserModule.MyUUIDModel')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File_name', models.TextField(blank=True)),
                ('Description', models.TextField(blank=True)),
                ('Creation_Date', models.DateField(null=True)),
                ('Member_Id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='UserModule.MyUUIDModel')),
            ],
        ),
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(blank=True)),
                ('Issuing_Org', models.TextField(null=True)),
                ('Issued_Date', models.DateField(null=True)),
                ('Expiration_Date', models.DateField(blank=True)),
                ('Credential_Id', models.CharField(blank=True, max_length=20)),
                ('Credential_URL', models.URLField(blank=True)),
                ('Description', models.TextField(blank=True)),
                ('Member_Id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='UserModule.MyUUIDModel')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dno', models.CharField(blank=True, max_length=10)),
                ('Street', models.TextField(blank=True)),
                ('City', models.TextField(blank=True)),
                ('State', models.TextField(blank=True)),
                ('Country', models.TextField(blank=True)),
                ('Pin_Code', models.IntegerField()),
                ('Member_Id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='UserModule.MyUUIDModel')),
            ],
        ),
    ]
