# Generated by Django 3.0.8 on 2020-08-07 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserModule', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Education',
            new_name='Edu',
        ),
    ]
