# Generated by Django 3.0.8 on 2020-08-07 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserModule', '0002_auto_20200807_2107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Edu',
            new_name='AcademicDetails',
        ),
        migrations.RenameModel(
            old_name='Certifications',
            new_name='Certificates',
        ),
        migrations.RenameModel(
            old_name='Documents',
            new_name='Document',
        ),
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.RenameModel(
            old_name='Testimonials',
            new_name='Testimonial',
        ),
    ]
