# Generated by Django 3.1 on 2020-08-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coupons', '0002_auto_20200821_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponadmin',
            name='code',
            field=models.CharField(default='72F982Q2', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='referralformember',
            name='code',
            field=models.CharField(default='QZWTHN', max_length=6, unique=True),
        ),
    ]
