# Generated by Django 3.0.8 on 2020-08-17 14:06

from django.db import migrations, models
import multi_email_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flatNo', models.CharField(blank=True, default='', max_length=10)),
                ('street', models.TextField(blank=True, default='', max_length=50)),
                ('city', models.TextField(blank=True, default='', max_length=30)),
                ('state', models.TextField(blank=True, default='', max_length=30)),
                ('country', models.TextField(blank=True, default='', max_length=20)),
                ('pinCode', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='')),
                ('issuingOrg', models.TextField(blank=True, default='')),
                ('issuedDate', models.DateField(null=True)),
                ('expiryDate', models.DateField(blank=True)),
                ('credentialId', models.TextField(blank=True, default='')),
                ('credentialUrl', models.URLField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='contactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails', multi_email_field.fields.MultiEmailField(default=[])),
                ('countryCode', models.IntegerField()),
                ('phone', models.CharField(blank=True, default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.TextField(blank=True, default='')),
                ('degree', models.CharField(blank=True, default='', max_length=50)),
                ('branch', models.TextField(blank=True, default='')),
                ('grade', models.FloatField()),
                ('startDate', models.DateField(null=True)),
                ('endDate', models.DateField(null=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images')),
                ('firstName', models.CharField(blank=True, default='', max_length=20)),
                ('lastName', models.CharField(blank=True, default='', max_length=20)),
                ('bio', models.TextField(blank=True, default='')),
                ('tagLine', models.TextField(blank=True, default='')),
                ('status', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.TextField(blank=True, default='')),
                ('speciality', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attestant', models.TextField(blank=True, default='')),
                ('issuedDate', models.DateField(null=True)),
                ('services', models.TextField(blank=True, default='')),
                ('designation', models.TextField(blank=True, default='')),
                ('location', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
    ]
