# Generated by Django 3.0.8 on 2020-08-20 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attestant', models.TextField(blank=True, default='')),
                ('issuedDate', models.DateField(null=True)),
                ('services', models.TextField(blank=True, default='')),
                ('designation', models.TextField(blank=True, default='')),
                ('location', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('userTestimonial', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userTestimonial', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.TextField(blank=True, max_length=100, null=True)),
                ('speciality', models.TextField(blank=True, max_length=100, null=True)),
                ('userSkills', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userSkills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('firstName', models.CharField(blank=True, default='', max_length=20)),
                ('lastName', models.CharField(blank=True, default='', max_length=20)),
                ('aboutMe', models.TextField(blank=True, default='', max_length=200)),
                ('tagLine', models.TextField(blank=True, default='', max_length=100)),
                ('status', models.TextField(blank=True, default='', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.TextField(blank=True, default='')),
                ('degree', models.CharField(blank=True, default='', max_length=50)),
                ('branch', models.TextField(blank=True, default='')),
                ('grade', models.FloatField()),
                ('startDate', models.DateField(null=True)),
                ('endDate', models.DateField(null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('userEducation', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userEducation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('userContact', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userContact', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='')),
                ('issuingOrg', models.TextField(blank=True, default='')),
                ('issuedDate', models.DateField(null=True)),
                ('expiryDate', models.DateField(blank=True)),
                ('credentialId', models.TextField(blank=True, default='')),
                ('credentialUrl', models.URLField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('userCertificate', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userCertificate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flatNo', models.CharField(blank=True, default='', max_length=20)),
                ('street', models.TextField(blank=True, default='', max_length=100)),
                ('city', models.TextField(blank=True, default='', max_length=30)),
                ('state', models.TextField(blank=True, default='', max_length=30)),
                ('country', models.TextField(blank=True, default='', max_length=20)),
                ('pinCode', models.IntegerField(blank=True)),
                ('userAddress', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userAddress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
