# Generated by Django 3.0.8 on 2020-08-21 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='userAddress',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='userCertificate',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='contactinfo',
            old_name='userContact',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='userEducation',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='userSkills',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='userTestimonial',
            new_name='user',
        ),
    ]
