# Generated by Django 3.0.8 on 2020-08-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20200817_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='education',
            name='user',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='user',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='firstName',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lastName',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='userprofile.jpg', upload_to='pics'),
        ),
        migrations.DeleteModel(
            name='address',
        ),
        migrations.DeleteModel(
            name='certificate',
        ),
        migrations.DeleteModel(
            name='contactInfo',
        ),
        migrations.DeleteModel(
            name='education',
        ),
        migrations.DeleteModel(
            name='skills',
        ),
        migrations.DeleteModel(
            name='testimonial',
        ),
    ]
