# Generated by Django 3.0.8 on 2020-08-19 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_auto_20200819_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactinfo',
            old_name='user',
            new_name='user1',
        ),
    ]
