# Generated by Django 3.1 on 2020-08-22 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(default='destination_4.jpg', upload_to='pics')),
                ('desc', models.TextField(default='Defualt Value')),
                ('price', models.IntegerField(default=0)),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DirectoryMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(blank=True, max_length=250)),
                ('Bio', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DirectoryMemberTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directorymems', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socius.directorymembers')),
            ],
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('coupon', models.CharField(blank=True, max_length=100, null=True)),
                ('is_superuser', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='memberdirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DirectoryName', models.CharField(blank=True, max_length=100, null=True)),
                ('img', models.ImageField(default='', upload_to='pics')),
                ('Description', models.TextField(default='Defualt Value')),
                ('MemberLimit', models.IntegerField(default=0)),
                ('directorymember', models.ManyToManyField(through='socius.DirectoryMemberTable', to='socius.DirectoryMembers')),
                ('user', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='directorymembertable',
            name='memdirectory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socius.memberdirectory'),
        ),
        migrations.AddField(
            model_name='directorymembers',
            name='Directory',
            field=models.ManyToManyField(through='socius.DirectoryMemberTable', to='socius.memberdirectory'),
        ),
        migrations.AddField(
            model_name='directorymembers',
            name='memberdirectory_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberdirectory_id', to='socius.memberdirectory'),
        ),
    ]
