# Generated by Django 3.1 on 2020-08-23 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socius', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorymembertable',
            name='loggedinuser',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loggedinuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
