# Generated by Django 3.1 on 2020-08-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socius', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdirectory',
            name='img',
            field=models.ImageField(default='', upload_to='pics'),
        ),
    ]
