# Generated by Django 3.1 on 2020-08-11 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socius', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField(blank=True)),
                ('Attestant', models.TextField(blank=True)),
                ('Date', models.DateField(null=True)),
                ('Designation', models.TextField(blank=True)),
                ('Location', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country_Code', models.IntegerField()),
                ('Phone', models.IntegerField()),
                ('Email_Id', models.EmailField(blank=True, max_length=320)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(blank=True, max_length=20)),
                ('Last_Name', models.CharField(blank=True, max_length=20)),
                ('Profile_Pic_URL', models.ImageField(upload_to='profile_pics')),
                ('Bio', models.TextField(blank=True)),
                ('Tag_Line', models.TextField(blank=True)),
                ('profile_Status', models.IntegerField(default=0)),
                ('Status', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KeySKills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skills', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_Title', models.TextField(blank=True)),
                ('Timings', models.DateTimeField(null=True)),
                ('Description', models.TextField(blank=True)),
                ('EventDate', models.DateField(null=True)),
                ('LinkToDoc', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File_name', models.TextField(blank=True)),
                ('Description', models.TextField(blank=True)),
                ('Creation_Date', models.DateField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(blank=True)),
                ('Issuing_Org', models.TextField(null=True)),
                ('Issued_Date', models.DateField(null=True)),
                ('Expiration_Date', models.DateField(blank=True)),
                ('Credential_Id', models.CharField(blank=True, max_length=20)),
                ('Credential_URL', models.URLField(blank=True)),
                ('Description', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dno', models.CharField(blank=True, max_length=10)),
                ('Street', models.TextField(blank=True)),
                ('City', models.TextField(blank=True)),
                ('State', models.TextField(blank=True)),
                ('Country', models.TextField(blank=True)),
                ('Pin_Code', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Institution_Name', models.CharField(blank=True, max_length=100)),
                ('Degree', models.CharField(blank=True, max_length=50)),
                ('Field_Of_Study', models.TextField(blank=True)),
                ('Grade', models.FloatField()),
                ('Start_Date', models.DateField(null=True)),
                ('End_Date', models.DateField(null=True)),
                ('Description', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
