# Generated by Django 3.1 on 2020-08-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socius', '0002_directorymembertable_loggedinuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberdirectory',
            name='Description',
            field=models.CharField(blank=True, default='Defualt Value', max_length=300, null=True),
        ),
    ]
