# Generated by Django 3.1 on 2020-08-19 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socius', '0002_memberdirectory_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberdirectory',
            old_name='desc',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='memberdirectory',
            old_name='name',
            new_name='DirectoryName',
        ),
        migrations.RenameField(
            model_name='memberdirectory',
            old_name='size',
            new_name='MemberLimit',
        ),
        migrations.AlterField(
            model_name='memberdirectory',
            name='user',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
