# Generated by Django 3.1 on 2020-08-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socius', '0002_auto_20200811_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='is_superuser',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
