# Generated by Django 3.1 on 2020-08-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socius', '0002_memberdirectory_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(blank=True, max_length=250)),
                ('Bio', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
