# Generated by Django 3.1 on 2020-08-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socius', '0003_auto_20200819_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorymembers',
            name='Directory',
            field=models.ManyToManyField(to='socius.memberdirectory'),
        ),
    ]
