# Generated by Django 3.1 on 2020-08-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socius', '0003_auto_20200812_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='memberdirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('desc', models.TextField(default='Defualt Value')),
                ('size', models.IntegerField(default=0)),
            ],
        ),
    ]
