# Generated by Django 3.1 on 2020-08-14 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multi_email_field.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socius', '0004_memberdirectory'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='')),
                ('issuingOrg', models.TextField(blank=True, default='')),
                ('issuedDate', models.DateField(null=True)),
                ('expiryDate', models.DateField(blank=True)),
                ('credentialId', models.TextField(blank=True, default='')),
                ('credentialUrl', models.URLField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='contactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails', multi_email_field.fields.MultiEmailField(default=[])),
                ('countryCode', models.IntegerField()),
                ('phone', models.CharField(blank=True, default='', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.TextField(blank=True, default='')),
                ('degree', models.CharField(blank=True, default='', max_length=50)),
                ('branch', models.TextField(blank=True, default='')),
                ('grade', models.FloatField()),
                ('startDate', models.DateField(null=True)),
                ('endDate', models.DateField(null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images')),
                ('firstName', models.CharField(blank=True, default='', max_length=20)),
                ('lastName', models.CharField(blank=True, default='', max_length=20)),
                ('bio', models.TextField(blank=True, default='')),
                ('tagLine', models.TextField(blank=True, default='')),
                ('status', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.TextField(blank=True, default='')),
                ('speciality', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='certificates',
            name='user',
        ),
        migrations.RemoveField(
            model_name='document',
            name='user',
        ),
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.RemoveField(
            model_name='keyskills',
            name='user',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='user',
        ),
        migrations.RemoveField(
            model_name='speciality',
            name='user',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='Date',
            new_name='issuedDate',
        ),
        migrations.RemoveField(
            model_name='address',
            name='City',
        ),
        migrations.RemoveField(
            model_name='address',
            name='Country',
        ),
        migrations.RemoveField(
            model_name='address',
            name='Dno',
        ),
        migrations.RemoveField(
            model_name='address',
            name='Pin_Code',
        ),
        migrations.RemoveField(
            model_name='address',
            name='State',
        ),
        migrations.RemoveField(
            model_name='address',
            name='Street',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='Attestant',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='Designation',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='Location',
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.TextField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.TextField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='address',
            name='flatNo',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='address',
            name='pinCode',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.TextField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.TextField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='attestant',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='designation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='location',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='services',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.DeleteModel(
            name='AcademicDetails',
        ),
        migrations.DeleteModel(
            name='Certificates',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='KeySKills',
        ),
        migrations.DeleteModel(
            name='MemberProfile',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
        migrations.DeleteModel(
            name='Speciality',
        ),
    ]
