# Generated by Django 3.1 on 2020-08-21 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socius', '0004_directorymembers_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorymembers',
            name='memberdirectory_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberdirectory_id', to='socius.memberdirectory'),
        ),
    ]
